// Comprehensive Astrological Dataset for AstroGPT
// Harmonizing Tropical Western Sun Signs with Vedic Jyotisha Rashis and Nakshatras

const SIGNS = [
  {
    id: "aries",
    name: "Aries",
    sanskrit: "Mesha",
    glyph: "♈",
    element: "Fire",
    vedicElement: "Agni",
    modality: "Cardinal",
    vedicModality: "Chara",
    ruler: "Mars",
    vedicRuler: "Mangala",
    dateRange: "Mar 21 – Apr 19",
    startMonth: 3,
    startDay: 21,
    endMonth: 4,
    endDay: 19,
    luckyDay: "Tuesday",
    luckyGem: "Red Coral / Diamond",
    luckyColor: "Crimson & Scarlet",
    luckyNumber: 9,
    traits: ["Bold", "Pioneering", "Courageous", "Dynamic", "Energetic"],
    strengths: "Natural leadership, fearlessness in starting new journeys, unwavering optimism.",
    growthEdge: "Cultivating patience and listening deeply before charging ahead.",
    summary: "The first sign of the zodiac represents primal vitality, leadership, and unbridled initiative."
  },
  {
    id: "taurus",
    name: "Taurus",
    sanskrit: "Vrishabha",
    glyph: "♉",
    element: "Earth",
    vedicElement: "Prithvi",
    modality: "Fixed",
    vedicModality: "Sthira",
    ruler: "Venus",
    vedicRuler: "Shukra",
    dateRange: "Apr 20 – May 20",
    startMonth: 4,
    startDay: 20,
    endMonth: 5,
    endDay: 20,
    luckyDay: "Friday",
    luckyGem: "Emerald / White Sapphire",
    luckyColor: "Forest Green & Rose",
    luckyNumber: 6,
    traits: ["Steadfast", "Sensual", "Loyal", "Grounded", "Artistic"],
    strengths: "Immense perseverance, loyalty, creating enduring beauty and security.",
    growthEdge: "Embracing change and letting go of rigid attachments.",
    summary: "Rooted in the earthly realm, Taurus builds beauty, comfort, and unshakable foundations."
  },
  {
    id: "gemini",
    name: "Gemini",
    sanskrit: "Mithuna",
    glyph: "♊",
    element: "Air",
    vedicElement: "Vayu",
    modality: "Mutable",
    vedicModality: "Dvisvabhava",
    ruler: "Mercury",
    vedicRuler: "Budha",
    dateRange: "May 21 – Jun 20",
    startMonth: 5,
    startDay: 21,
    endMonth: 6,
    endDay: 20,
    luckyDay: "Wednesday",
    luckyGem: "Emerald / Green Tourmaline",
    luckyColor: "Golden Yellow & Light Blue",
    luckyNumber: 5,
    traits: ["Curious", "Articulate", "Adaptable", "Witty", "Perceptive"],
    strengths: "Quick-witted communication, multidimensional curiosity, bridging divergent ideas.",
    growthEdge: "Channeling scattered mental energies into singular deep focus.",
    summary: "The sign of swift intellectual exchange, curiosity, and dual perspective."
  },
  {
    id: "cancer",
    name: "Cancer",
    sanskrit: "Karka",
    glyph: "♋",
    element: "Water",
    vedicElement: "Jala",
    modality: "Cardinal",
    vedicModality: "Chara",
    ruler: "Moon",
    vedicRuler: "Chandra",
    dateRange: "Jun 21 – Jul 22",
    startMonth: 6,
    startDay: 21,
    endMonth: 7,
    endDay: 22,
    luckyDay: "Monday",
    luckyGem: "Pearl / Moonstone",
    luckyColor: "Silver & Seafoam White",
    luckyNumber: 2,
    traits: ["Intuitive", "Nurturing", "Empathetic", "Protective", "Imaginative"],
    strengths: "Profound emotional resonance, protective care for loved ones, deep creative memory.",
    growthEdge: "Establishing emotional boundaries without retreating into defensive shells.",
    summary: "Governed by the luminous tides of the Moon, Cancer offers sanctuary and deep emotional wisdom."
  },
  {
    id: "leo",
    name: "Leo",
    sanskrit: "Simha",
    glyph: "♌",
    element: "Fire",
    vedicElement: "Agni",
    modality: "Fixed",
    vedicModality: "Sthira",
    ruler: "Sun",
    vedicRuler: "Surya",
    dateRange: "Jul 23 – Aug 22",
    startMonth: 7,
    startDay: 23,
    endMonth: 8,
    endDay: 22,
    luckyDay: "Sunday",
    luckyGem: "Ruby / Amber",
    luckyColor: "Solar Gold & Royal Purple",
    luckyNumber: 1,
    traits: ["Radiant", "Generous", "Charismatic", "Warm", "Noble"],
    strengths: "Magnanimous heart, creative self-expression, inspiring confidence in others.",
    growthEdge: "Cultivating humility and sharing the spotlight gracefully.",
    summary: "The regal flame of the Sun, Leo embodies warm generosity, sovereignty, and creative brilliance."
  },
  {
    id: "virgo",
    name: "Virgo",
    sanskrit: "Kanya",
    glyph: "♍",
    element: "Earth",
    vedicElement: "Prithvi",
    modality: "Mutable",
    vedicModality: "Dvisvabhava",
    ruler: "Mercury",
    vedicRuler: "Budha",
    dateRange: "Aug 23 – Sep 22",
    startMonth: 8,
    startDay: 23,
    endMonth: 9,
    endDay: 22,
    luckyDay: "Wednesday",
    luckyGem: "Peridot / Jade",
    luckyColor: "Earthy Ochre & Moss Green",
    luckyNumber: 5,
    traits: ["Analytical", "Helpful", "Precise", "Devoted", "Discerning"],
    strengths: "Meticulous discernment, healing capacity, practical mastery and selfless service.",
    growthEdge: "Releasing impossible perfectionism and celebrating incremental milestones.",
    summary: "Dedicated to the craft of discernment, purification, and heartfelt service."
  },
  {
    id: "libra",
    name: "Libra",
    sanskrit: "Tula",
    glyph: "♎",
    element: "Air",
    vedicElement: "Vayu",
    modality: "Cardinal",
    vedicModality: "Chara",
    ruler: "Venus",
    vedicRuler: "Shukra",
    dateRange: "Sep 23 – Oct 22",
    startMonth: 9,
    startDay: 23,
    endMonth: 10,
    endDay: 22,
    luckyDay: "Friday",
    luckyGem: "Opal / Diamond",
    luckyColor: "Pastel Blue & Rose Gold",
    luckyNumber: 6,
    traits: ["Harmonious", "Diplomatic", "Fair", "Charming", "Refined"],
    strengths: "Creating peaceful equilibrium, aesthetic elegance, objective mediation.",
    growthEdge: "Asserting clear personal desires without fearing conflict.",
    summary: "The cosmic scales of balance, diplomacy, relationship wisdom, and harmonic beauty."
  },
  {
    id: "scorpio",
    name: "Scorpio",
    sanskrit: "Vrishchika",
    glyph: "♏",
    element: "Water",
    vedicElement: "Jala",
    modality: "Fixed",
    vedicModality: "Sthira",
    ruler: "Mars & Pluto",
    vedicRuler: "Mangala & Ketu",
    dateRange: "Oct 23 – Nov 21",
    startMonth: 10,
    startDay: 23,
    endMonth: 11,
    endDay: 21,
    luckyDay: "Tuesday",
    luckyGem: "Red Coral / Bloodstone",
    luckyColor: "Deep Burgundy & Obsidian Black",
    luckyNumber: 9,
    traits: ["Intense", "Transformative", "Perceptive", "Passionate", "Resilient"],
    strengths: "Uncanny psychological insight, profound loyalty, capacity to regenerate through trials.",
    growthEdge: "Releasing resentments and trusting the vulnerability of open connection.",
    summary: "Master of transformation, regenerative depth, and penetrating perception into hidden truths."
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    sanskrit: "Dhanu",
    glyph: "♐",
    element: "Fire",
    vedicElement: "Agni",
    modality: "Mutable",
    vedicModality: "Dvisvabhava",
    ruler: "Jupiter",
    vedicRuler: "Guru",
    dateRange: "Nov 22 – Dec 21",
    startMonth: 11,
    startDay: 22,
    endMonth: 12,
    endDay: 21,
    luckyDay: "Thursday",
    luckyGem: "Yellow Sapphire / Topaz",
    luckyColor: "Royal Indigo & Saffron",
    luckyNumber: 3,
    traits: ["Philosophical", "Adventurous", "Optimistic", "Free-spirited", "Honest"],
    strengths: "Broad perspective, quest for higher truth, infectious enthusiasm and generosity.",
    growthEdge: "Grounding boundless idealism into disciplined follow-through.",
    summary: "The archer seeking the distant horizon, guided by wisdom, expansive faith, and exploration."
  },
  {
    id: "capricorn",
    name: "Capricorn",
    sanskrit: "Makara",
    glyph: "♑",
    element: "Earth",
    vedicElement: "Prithvi",
    modality: "Cardinal",
    vedicModality: "Chara",
    ruler: "Saturn",
    vedicRuler: "Shani",
    dateRange: "Dec 22 – Jan 19",
    startMonth: 12,
    startDay: 22,
    endMonth: 1,
    endDay: 19,
    luckyDay: "Saturday",
    luckyGem: "Blue Sapphire / Garnet",
    luckyColor: "Charcoal Gray & Navy Blue",
    luckyNumber: 8,
    traits: ["Disciplined", "Strategic", "Patient", "Authoritative", "Enduring"],
    strengths: "Exceptional fortitude, architectural vision, mastery over time and sustained effort.",
    growthEdge: "Making time for play, warmth, and gentle self-compassion.",
    summary: "Ascending the summit step by step, Capricorn builds enduring monuments with patience."
  },
  {
    id: "aquarius",
    name: "Aquarius",
    sanskrit: "Kumbha",
    glyph: "♒",
    element: "Air",
    vedicElement: "Vayu",
    modality: "Fixed",
    vedicModality: "Sthira",
    ruler: "Saturn & Uranus",
    vedicRuler: "Shani & Rahu",
    dateRange: "Jan 20 – Feb 18",
    startMonth: 1,
    startDay: 20,
    endMonth: 2,
    endDay: 18,
    luckyDay: "Saturday",
    luckyGem: "Amethyst / Blue Sapphire",
    luckyColor: "Electric Cyan & Ultramarine",
    luckyNumber: 4,
    traits: ["Visionary", "Humanitarian", "Innovative", "Independent", "Original"],
    strengths: "Forward-thinking insight, democratic camaraderie, unshakeable originality.",
    growthEdge: "Bridging the gap between universal concepts and intimate personal warmth.",
    summary: "The water-bearer pouring out the waters of collective enlightenment and visionary change."
  },
  {
    id: "pisces",
    name: "Pisces",
    sanskrit: "Meena",
    glyph: "♓",
    element: "Water",
    vedicElement: "Jala",
    modality: "Mutable",
    vedicModality: "Dvisvabhava",
    ruler: "Jupiter & Neptune",
    vedicRuler: "Guru",
    dateRange: "Feb 19 – Mar 20",
    startMonth: 2,
    startDay: 19,
    endMonth: 3,
    endDay: 20,
    luckyDay: "Thursday",
    luckyGem: "Yellow Sapphire / Aquamarine",
    luckyColor: "Sea Green & Lavender",
    luckyNumber: 7,
    traits: ["Compassionate", "Mystical", "Artistic", "Dreamy", "Empathetic"],
    strengths: "Boundless empathy, connection to the transcendent, poetic imagination.",
    growthEdge: "Anchoring mystical reverie with practical everyday reality.",
    summary: "The final sign dissolving boundaries, uniting wisdom, cosmic empathy, and artistic vision."
  }
];

const NAKSHATRAS = [
  { name: "Ashwini", ruler: "Ketu", deity: "Ashwini Kumaras", sign: "Aries", symbol: "Horse's Head", span: "0°00′ - 13°20′ Aries" },
  { name: "Bharani", ruler: "Venus", deity: "Yama", sign: "Aries", symbol: "Yoni", span: "13°20′ - 26°40′ Aries" },
  { name: "Krittika", ruler: "Sun", deity: "Agni", sign: "Aries / Taurus", symbol: "Razor / Flame", span: "26°40′ Aries - 10°00′ Taurus" },
  { name: "Rohini", ruler: "Moon", deity: "Brahma", sign: "Taurus", symbol: "Cart / Chariot", span: "10°00′ - 23°20′ Taurus" },
  { name: "Mrigashira", ruler: "Mars", deity: "Soma", sign: "Taurus / Gemini", symbol: "Deer's Head", span: "23°20′ Taurus - 6°40′ Gemini" },
  { name: "Ardra", ruler: "Rahu", deity: "Rudra", sign: "Gemini", symbol: "Teardrop", span: "6°40′ - 20°00′ Gemini" },
  { name: "Punarvasu", ruler: "Jupiter", deity: "Aditi", sign: "Gemini / Cancer", symbol: "Bow & Quiver", span: "20°00′ Gemini - 3°20′ Cancer" },
  { name: "Pushya", ruler: "Saturn", deity: "Brihaspati", sign: "Cancer", symbol: "Cow's Udder / Lotus", span: "3°20′ - 16°40′ Cancer" },
  { name: "Ashlesha", ruler: "Mercury", deity: "Sarpas", sign: "Cancer", symbol: "Coiled Serpent", span: "16°40′ - 30°00′ Cancer" },
  { name: "Magha", ruler: "Ketu", deity: "Pitris", sign: "Leo", symbol: "Royal Throne", span: "0°00′ - 13°20′ Leo" },
  { name: "Purva Phalguni", ruler: "Venus", deity: "Bhaga", sign: "Leo", symbol: "Front of Bed", span: "13°20′ - 26°40′ Leo" },
  { name: "Uttara Phalguni", ruler: "Sun", deity: "Aryaman", sign: "Leo / Virgo", symbol: "Back of Bed", span: "26°40′ Leo - 10°00′ Virgo" },
  { name: "Hasta", ruler: "Moon", deity: "Savitr", sign: "Virgo", symbol: "Hand / Open Palm", span: "10°00′ - 23°20′ Virgo" },
  { name: "Chitra", ruler: "Mars", deity: "Tvashtar", sign: "Virgo / Libra", symbol: "Bright Jewel", span: "23°20′ Virgo - 6°40′ Libra" },
  { name: "Swati", ruler: "Rahu", deity: "Vayu", sign: "Libra", symbol: "Young Shoot / Coral", span: "6°40′ - 20°00′ Libra" },
  { name: "Vishakha", ruler: "Jupiter", deity: "Indra-Agni", sign: "Libra / Scorpio", symbol: "Triumphal Arch", span: "20°00′ Libra - 3°20′ Scorpio" },
  { name: "Anuradha", ruler: "Saturn", deity: "Mitra", sign: "Scorpio", symbol: "Lotus Flower", span: "3°20′ - 16°40′ Scorpio" },
  { name: "Jyeshtha", ruler: "Mercury", deity: "Indra", sign: "Scorpio", symbol: "Circular Amulet", span: "16°40′ - 30°00′ Scorpio" },
  { name: "Mula", ruler: "Ketu", deity: "Nirriti", sign: "Sagittarius", symbol: "Tied Bunch of Roots", span: "0°00′ - 13°20′ Sagittarius" },
  { name: "Purva Ashadha", ruler: "Venus", deity: "Apas", sign: "Sagittarius", symbol: "Elephant Tusk / Fan", span: "13°20′ - 26°40′ Sagittarius" },
  { name: "Uttara Ashadha", ruler: "Sun", deity: "Vishwadevas", sign: "Sagittarius / Capricorn", symbol: "Planks / Small Cot", span: "26°40′ Sag - 10°00′ Capricorn" },
  { name: "Shravana", ruler: "Moon", deity: "Vishnu", sign: "Capricorn", symbol: "Three Footprints / Ear", span: "10°00′ - 23°20′ Capricorn" },
  { name: "Dhanishtha", ruler: "Mars", deity: "Eight Vasus", sign: "Capricorn / Aquarius", symbol: "Drum / Flute", span: "23°20′ Cap - 6°40′ Aquarius" },
  { name: "Shatabhisha", ruler: "Rahu", deity: "Varuna", sign: "Aquarius", symbol: "Empty Circle / 100 Physicians", span: "6°40′ - 20°00′ Aquarius" },
  { name: "Purva Bhadrapada", ruler: "Jupiter", deity: "Aja Ekapada", sign: "Aquarius / Pisces", symbol: "Front of Funeral Cot", span: "20°00′ Aqu - 3°20′ Pisces" },
  { name: "Uttara Bhadrapada", ruler: "Saturn", deity: "Ahirbudhnya", sign: "Pisces", symbol: "Back of Funeral Cot", span: "3°20′ - 16°40′ Pisces" },
  { name: "Revati", ruler: "Mercury", deity: "Pushan", sign: "Pisces", symbol: "Pair of Fish / Drum", span: "16°40′ - 30°00′ Pisces" }
];

// Determine sign from month (1-12) and day (1-31)
function getSignByDate(month, day) {
  for (const sign of SIGNS) {
    if (sign.startMonth === sign.endMonth) {
      if (month === sign.startMonth && day >= sign.startDay && day <= sign.endDay) {
        return sign;
      }
    } else if (sign.startMonth > sign.endMonth) {
      // Crossing year boundary (e.g. Capricorn Dec 22 - Jan 19)
      if ((month === sign.startMonth && day >= sign.startDay) || (month === sign.endMonth && day <= sign.endDay)) {
        return sign;
      }
    } else {
      if (
        (month === sign.startMonth && day >= sign.startDay) ||
        (month === sign.endMonth && day <= sign.endDay) ||
        (month > sign.startMonth && month < sign.endMonth)
      ) {
        return sign;
      }
    }
  }
  return SIGNS[0]; // fallback
}

// Generate personalized horoscope reading based on sign and date
function generateDailyReading(sign, dateStr) {
  const seeds = [
    `Today highlights your ${sign.element.toLowerCase()} elemental strength. A thoughtful initiative started before noon will bear constructive fruits.`,
    `Your ruling planet ${sign.ruler} aligns favorably today, illuminating a creative breakthrough. Speak your intentions clearly.`,
    `The cosmic winds favor steady focus today. Your natural ${sign.traits[0].toLowerCase()} energy helps turn a complex situation into clarity.`,
    `A balanced conversation brings unexpected inspiration today. Take time to honor both your personal needs and shared commitments.`,
    `Trust your intuitive discernment today. A quiet moment of reflection will reveal the exact path through an unresolved puzzle.`
  ];
  const dateNum = (dateStr || "").split("-").reduce((acc, part) => acc + Number(part || 0), 0);
  const signIndex = SIGNS.findIndex(s => s.id === sign.id);
  return seeds[(dateNum + signIndex) % seeds.length];
}

module.exports = {
  SIGNS,
  NAKSHATRAS,
  getSignByDate,
  generateDailyReading
};
